from __future__ import annotations

from pathlib import Path
from textwrap import indent

from .models import TestStubRequest


class StubWriter:
    """Writes pytest-style placeholder tests for missing modules."""

    def __init__(self, repo_root: Path, output_dir: Path | None = None) -> None:
        self.repo_root = repo_root
        self.output_root = output_dir or (repo_root / ".generated_tests")

    def write(self, plans: list[TestStubRequest], overwrite: bool = False) -> list[Path]:
        written: list[Path] = []
        for plan in plans:
            destination = self.output_root / plan.test_relative_path
            if destination.exists() and not overwrite:
                continue
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(self._render_stub(plan), encoding="utf-8")
            written.append(destination)
        return written

    def _render_stub(self, plan: TestStubRequest) -> str:
        header = (
            "# Auto-generated by testgap.\n"
            f"# Source: {plan.module.display_name}\n"
        )

        imports = f"from {plan.module.module_import} import (\n"
        symbol_list = ",\n".join(f"    {name}" for name in plan.iter_symbol_names())
        imports += symbol_list + "\n)\n\n"
        body_parts = ["import pytest\n", imports]

        for symbol in plan.targets:
            test_name = f"test_{symbol.name}_behavior"
            body_parts.append(f"def {test_name}():\n")
            message = (
                f"Implement tests for {symbol.kind} '{symbol.name}' "
                f"in module {plan.module.module_import}"
            )
            body_parts.append(indent(f"pytest.fail({message!r})\n\n", "    "))

        return header + "".join(body_parts)
